2021-03-13 23:22:17,227 INFO    Thread-11 :1776 [wandb_setup.py:_flush():69] setting env: {'root_dir': 'C:\\Users\\rigve\\Documents\\IITM\\Courses\\DL 6910\\Github\\CS6910\\Assignment 1', 'sweep_id': 'imakrin1', 'project': 'Assignment 1', 'run_id': 'q0ffn1tk', 'sweep_param_path': 'C:\\Users\\rigve\\Documents\\IITM\\Courses\\DL 6910\\Github\\CS6910\\Assignment 1\\wandb\\sweep-imakrin1\\config-q0ffn1tk.yaml'}
2021-03-13 23:22:17,227 INFO    Thread-11 :1776 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 23:22:17,227 INFO    Thread-11 :1776 [wandb_init.py:_log_setup():334] Logging user logs to C:\Users\rigve\Documents\IITM\Courses\DL 6910\Github\CS6910\Assignment 1\wandb\run-20210313_232217-q0ffn1tk\logs\debug.log
2021-03-13 23:22:17,229 INFO    Thread-11 :1776 [wandb_init.py:_log_setup():335] Logging internal logs to C:\Users\rigve\Documents\IITM\Courses\DL 6910\Github\CS6910\Assignment 1\wandb\run-20210313_232217-q0ffn1tk\logs\debug-internal.log
2021-03-13 23:22:17,229 INFO    Thread-11 :1776 [wandb_init.py:_jupyter_setup():285] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000018D86644130>
2021-03-13 23:22:17,230 INFO    Thread-11 :1776 [wandb_init.py:init():367] calling init triggers
2021-03-13 23:22:17,230 INFO    Thread-11 :1776 [wandb_init.py:init():372] wandb.init called with sweep_config: {'ac': 'sig', 'batch_size': 64, 'epochs': 5, 'hidden_layer_size': 128, 'hidden_layers': 4, 'init_strategy': 'xavier', 'learning_rate': 0.001, 'optimiser': 'rmsprop', 'weight_decay': 0.5}
config: {}
2021-03-13 23:22:17,230 INFO    Thread-11 :1776 [wandb_init.py:init():416] starting backend
2021-03-13 23:22:17,230 INFO    Thread-11 :1776 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn, using: spawn
2021-03-13 23:22:17,234 INFO    Thread-11 :1776 [backend.py:ensure_launched():123] starting backend process...
2021-03-13 23:22:17,312 INFO    Thread-11 :1776 [backend.py:ensure_launched():127] started backend process with pid: 1584
2021-03-13 23:22:17,313 INFO    Thread-11 :1776 [wandb_init.py:init():421] backend started and connected
2021-03-13 23:22:17,357 INFO    Thread-11 :1776 [wandb_run.py:_config_callback():733] config_cb None None {'ac': 'sig', 'batch_size': 64, 'epochs': 5, 'hidden_layer_size': 128, 'hidden_layers': 4, 'init_strategy': 'xavier', 'learning_rate': 0.001, 'optimiser': 'rmsprop', 'weight_decay': 0.5}
2021-03-13 23:22:17,358 INFO    Thread-11 :1776 [wandb_init.py:init():461] updated telemetry
2021-03-13 23:22:17,359 INFO    Thread-11 :1776 [wandb_init.py:init():480] communicating current version
2021-03-13 23:22:18,351 INFO    Thread-11 :1776 [wandb_init.py:init():485] got version response 
2021-03-13 23:22:18,351 INFO    Thread-11 :1776 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-03-13 23:22:19,200 INFO    Thread-11 :1776 [wandb_init.py:init():513] run resumed
2021-03-13 23:22:19,203 INFO    Thread-11 :1776 [wandb_init.py:init():518] starting run threads in backend
2021-03-13 23:22:21,404 INFO    Thread-11 :1776 [wandb_run.py:_console_start():1480] atexit reg
2021-03-13 23:22:21,404 INFO    Thread-11 :1776 [wandb_run.py:_redirect():1343] redirect: SettingsConsole.WRAP
2021-03-13 23:22:21,405 INFO    Thread-11 :1776 [wandb_run.py:_redirect():1378] Wrapping output streams.
2021-03-13 23:22:21,405 INFO    Thread-11 :1776 [wandb_run.py:_redirect():1394] Redirects installed.
2021-03-13 23:22:21,405 INFO    Thread-11 :1776 [wandb_init.py:init():542] run started, returning control to user process
2021-03-13 23:39:26,338 ERROR   Thread-10 :1776 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:39:26,338 ERROR   Thread-10 :1776 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:39:27,885 ERROR   Thread-10 :1776 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:39:27,885 ERROR   Thread-10 :1776 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:39:56,835 ERROR   Thread-10 :1776 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:39:56,836 ERROR   Thread-10 :1776 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:39:59,402 ERROR   Thread-10 :1776 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:39:59,403 ERROR   Thread-10 :1776 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:40:13,577 ERROR   Thread-10 :1776 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:40:13,578 ERROR   Thread-10 :1776 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:40:28,777 ERROR   Thread-10 :1776 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:40:28,777 ERROR   Thread-10 :1776 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:40:43,813 ERROR   Thread-10 :1776 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:40:43,813 ERROR   Thread-10 :1776 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:40:58,431 ERROR   Thread-10 :1776 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:40:58,432 ERROR   Thread-10 :1776 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:41:13,569 ERROR   Thread-10 :1776 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:41:13,569 ERROR   Thread-10 :1776 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:41:24,105 INFO    Thread-11 :1776 [wandb_run.py:finish():1139] finishing run rigvedsah/Assignment 1/q0ffn1tk
