2021-03-13 23:33:51,250 INFO    Thread-8  :23168 [wandb_setup.py:_flush():69] setting env: {'root_dir': 'C:\\Users\\rigve\\Documents\\IITM\\Courses\\DL 6910\\Github\\CS6910\\Assignment 1', 'sweep_id': 'imakrin1', 'project': 'Assignment 1', 'run_id': 'jdbgkj6u', 'sweep_param_path': 'C:\\Users\\rigve\\Documents\\IITM\\Courses\\DL 6910\\Github\\CS6910\\Assignment 1\\wandb\\sweep-imakrin1\\config-jdbgkj6u.yaml'}
2021-03-13 23:33:51,250 INFO    Thread-8  :23168 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 23:33:51,252 INFO    Thread-8  :23168 [wandb_init.py:_log_setup():334] Logging user logs to C:\Users\rigve\Documents\IITM\Courses\DL 6910\Github\CS6910\Assignment 1\wandb\run-20210313_233351-jdbgkj6u\logs\debug.log
2021-03-13 23:33:51,252 INFO    Thread-8  :23168 [wandb_init.py:_log_setup():335] Logging internal logs to C:\Users\rigve\Documents\IITM\Courses\DL 6910\Github\CS6910\Assignment 1\wandb\run-20210313_233351-jdbgkj6u\logs\debug-internal.log
2021-03-13 23:33:51,253 INFO    Thread-8  :23168 [wandb_init.py:init():367] calling init triggers
2021-03-13 23:33:51,253 INFO    Thread-8  :23168 [wandb_init.py:init():372] wandb.init called with sweep_config: {'ac': 'relu', 'batch_size': 16, 'epochs': 5, 'hidden_layer_size': 128, 'hidden_layers': 5, 'init_strategy': 'xavier', 'learning_rate': 0.001, 'optimiser': 'nag', 'weight_decay': 0}
config: {}
2021-03-13 23:33:51,253 INFO    Thread-8  :23168 [wandb_init.py:init():416] starting backend
2021-03-13 23:33:51,253 INFO    Thread-8  :23168 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn, using: spawn
2021-03-13 23:33:51,257 INFO    Thread-8  :23168 [backend.py:ensure_launched():123] starting backend process...
2021-03-13 23:33:51,320 INFO    Thread-8  :23168 [backend.py:ensure_launched():127] started backend process with pid: 10812
2021-03-13 23:33:51,320 INFO    Thread-8  :23168 [wandb_init.py:init():421] backend started and connected
2021-03-13 23:33:51,321 INFO    Thread-8  :23168 [wandb_run.py:_config_callback():733] config_cb None None {'ac': 'relu', 'batch_size': 16, 'epochs': 5, 'hidden_layer_size': 128, 'hidden_layers': 5, 'init_strategy': 'xavier', 'learning_rate': 0.001, 'optimiser': 'nag', 'weight_decay': 0}
2021-03-13 23:33:51,321 INFO    Thread-8  :23168 [wandb_init.py:init():461] updated telemetry
2021-03-13 23:33:51,322 INFO    Thread-8  :23168 [wandb_init.py:init():480] communicating current version
2021-03-13 23:33:52,334 INFO    Thread-8  :23168 [wandb_init.py:init():485] got version response 
2021-03-13 23:33:52,334 INFO    Thread-8  :23168 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-03-13 23:33:53,305 INFO    Thread-8  :23168 [wandb_init.py:init():513] run resumed
2021-03-13 23:33:53,309 INFO    Thread-8  :23168 [wandb_init.py:init():518] starting run threads in backend
2021-03-13 23:33:56,176 INFO    Thread-8  :23168 [wandb_run.py:_console_start():1480] atexit reg
2021-03-13 23:33:56,178 INFO    Thread-8  :23168 [wandb_run.py:_redirect():1343] redirect: SettingsConsole.WRAP
2021-03-13 23:33:56,178 INFO    Thread-8  :23168 [wandb_run.py:_redirect():1378] Wrapping output streams.
2021-03-13 23:33:56,178 INFO    Thread-8  :23168 [wandb_run.py:_redirect():1394] Redirects installed.
2021-03-13 23:33:56,178 INFO    Thread-8  :23168 [wandb_init.py:init():542] run started, returning control to user process
2021-03-13 23:39:26,431 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:39:26,432 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:39:28,015 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:39:28,015 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:39:56,812 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:39:56,812 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:39:58,433 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:39:58,434 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:40:13,676 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:40:13,677 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:40:28,996 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:40:28,996 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:40:43,587 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:40:43,587 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:40:58,757 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:40:58,758 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:41:13,773 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:41:13,773 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:41:28,768 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:41:28,768 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:41:58,843 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:41:58,843 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:42:14,192 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:42:14,192 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:42:27,363 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:42:27,363 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:42:28,868 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:42:28,868 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:42:43,396 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:42:43,404 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:42:44,889 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:42:44,889 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:43:12,261 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:43:12,266 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:43:13,867 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:43:13,867 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:43:28,532 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:43:28,533 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:44:13,760 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:44:13,760 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:44:42,967 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:44:42,967 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:44:44,453 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:44:44,453 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:44:59,399 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:44:59,399 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:45:13,081 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:45:13,081 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:45:14,605 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:45:14,605 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:45:42,810 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:45:42,811 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:45:44,576 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:45:44,580 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:45:59,000 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:45:59,001 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:46:12,706 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:46:12,706 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:46:14,358 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:46:14,358 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:46:28,735 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:46:28,735 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:47:28,623 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:47:28,623 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:47:44,599 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:47:44,604 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:47:58,716 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:47:58,716 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:48:28,469 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:48:28,469 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:48:44,621 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:48:44,621 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:48:58,913 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:48:58,913 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:49:14,008 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:49:14,016 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:49:29,430 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:49:29,430 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:49:57,598 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:49:57,599 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:49:59,442 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:49:59,442 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:50:13,448 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:50:13,461 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:50:28,768 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:50:28,780 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:50:43,890 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:50:43,903 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:50:55,707 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:50:55,712 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:50:57,408 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:50:57,409 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:51:25,577 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:51:25,587 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:51:27,202 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:51:27,202 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:51:55,878 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:51:55,888 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:51:57,476 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:51:57,477 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:52:14,795 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:52:14,796 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:52:26,071 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:52:26,081 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:52:27,758 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:52:27,759 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:52:43,836 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:52:43,845 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:52:56,717 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:52:56,718 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:52:58,395 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:52:58,406 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:53:14,384 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:53:14,386 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:53:28,463 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:53:28,473 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:53:42,411 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:53:42,411 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:53:44,027 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:53:44,028 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:53:56,357 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:53:56,358 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:53:57,936 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:53:57,936 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:54:14,381 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:54:14,382 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:54:26,122 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:54:26,122 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:54:27,605 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:54:27,607 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:54:44,135 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:54:44,154 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:54:57,260 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:54:57,272 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:54:59,061 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:54:59,062 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:55:11,759 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:55:11,760 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:55:13,347 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:55:13,359 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:55:26,256 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:55:26,257 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:55:28,069 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:55:28,070 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:55:44,421 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:55:44,422 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:55:55,979 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:55:55,980 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:55:57,825 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:55:57,826 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:56:13,663 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:56:13,664 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:56:27,411 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:56:27,412 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:56:29,058 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:56:29,060 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:56:42,529 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:56:42,530 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:56:44,172 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:56:44,173 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:56:55,881 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:56:55,882 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:56:57,365 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:56:57,367 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:57:14,269 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:57:14,270 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:57:25,920 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:57:25,921 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:57:27,598 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:57:27,599 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:57:57,661 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:57:57,663 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:57:59,158 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:57:59,159 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:58:12,383 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:58:12,383 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:58:13,982 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:58:13,982 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:58:26,231 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:58:26,233 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:58:27,781 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:58:27,782 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:58:44,314 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:58:44,315 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:58:56,021 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:58:56,022 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:58:57,737 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:58:57,738 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:59:26,503 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:59:26,505 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:59:27,946 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:59:27,947 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:59:42,902 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:59:42,903 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:59:44,661 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:59:44,662 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:59:56,269 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:59:56,270 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-13 23:59:57,861 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-13 23:59:57,862 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:00:14,652 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:00:14,653 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:00:26,375 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:00:26,377 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:00:27,944 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:00:27,945 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:00:43,786 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:00:43,787 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:00:56,593 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:00:56,594 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:00:58,192 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:00:58,194 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:01:11,446 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:01:11,447 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:01:12,966 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:01:12,982 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:01:28,663 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:01:28,671 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:01:42,946 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:01:42,968 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:01:44,602 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:01:44,603 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:01:57,528 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:01:57,530 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:01:59,159 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:01:59,160 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:02:12,027 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:02:12,038 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:02:13,653 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:02:13,653 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:02:25,999 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:02:25,999 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:02:27,845 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:02:27,847 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:02:43,542 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:02:43,544 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:02:57,123 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:02:57,123 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:02:58,776 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:02:58,777 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:03:12,786 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:03:12,787 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:03:14,401 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:03:14,402 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:03:26,474 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:03:26,475 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:03:28,076 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:03:28,076 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:03:43,863 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:03:43,864 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:03:56,076 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:03:56,077 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:03:57,726 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:03:57,727 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:04:15,028 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:04:15,029 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:04:28,556 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:04:28,565 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:04:42,699 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:04:42,700 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:04:44,357 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:04:44,357 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:04:57,135 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:04:57,136 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:04:58,721 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:04:58,722 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:05:13,132 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:05:13,133 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:05:14,737 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:05:14,746 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:05:27,493 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:05:27,494 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:05:29,178 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:05:29,179 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:05:43,134 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:05:43,135 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:05:44,794 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:05:44,795 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:05:57,259 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:05:57,269 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:05:58,909 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:05:58,918 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:06:11,327 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:06:11,337 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:06:13,171 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:06:13,172 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:06:30,003 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:06:30,003 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:06:41,671 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:06:41,681 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:06:43,491 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:06:43,509 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:06:59,802 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:06:59,803 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:07:11,628 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:07:11,630 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:07:13,375 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:07:13,382 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:07:29,651 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:07:29,651 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:07:41,450 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:07:41,451 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:07:43,312 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:07:43,325 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:08:12,110 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:08:12,121 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:08:13,832 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:08:13,832 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:08:26,578 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:08:26,578 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:08:28,262 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:08:28,262 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:08:44,360 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:08:44,374 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:08:57,826 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:08:57,840 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:08:59,835 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:08:59,836 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:09:12,782 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:09:12,797 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:09:14,585 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:09:14,595 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:09:29,002 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:09:29,014 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:09:41,606 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:09:41,607 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:09:43,170 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:09:43,177 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:10:11,739 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:10:11,747 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:10:13,356 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:10:13,357 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:10:28,256 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:10:28,268 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:10:29,830 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:10:29,831 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:10:43,108 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:10:43,109 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:10:44,857 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:10:44,858 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:10:58,484 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:10:58,494 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:11:00,028 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:11:00,029 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:11:12,596 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:11:12,597 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:11:14,176 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:11:14,177 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:11:26,904 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:11:26,905 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:11:28,668 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:11:28,668 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:11:43,916 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:11:43,928 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:11:56,764 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:11:56,765 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:11:58,461 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:11:58,475 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:12:11,424 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:12:11,425 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:12:13,277 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:12:13,288 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:12:29,608 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:12:29,615 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:12:41,018 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:12:41,029 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:12:42,975 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:12:42,976 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:12:58,848 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:12:58,858 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:13:14,391 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:13:14,402 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:13:25,846 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:13:25,847 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:13:27,492 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:13:27,493 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:13:43,656 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:13:43,669 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:13:57,554 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:13:57,566 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

2021-03-14 00:13:59,255 ERROR   Thread-7  :23168 [internal_api.py:execute():126] 429 response executing GraphQL.
2021-03-14 00:13:59,256 ERROR   Thread-7  :23168 [internal_api.py:execute():127] {"error":"rate limit exceeded"}

